version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: db-postgre-local
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dosa_local
    volumes:
      - pgdata_local:/var/lib/postgresql/data

volumes:
  pgdata_local:
