version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: db-postgre-local
    restart: unless-stopped
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dosa_local
    volumes:
      - pgdata_local:/var/lib/postgresql/data

volumes:
  pgdata_local:
